name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 
      - name: Install Yarn
        run: npm install -g yarn
      - name: creates output
        run: sh ./bookduck/build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }} 
        with:
          source-directory: 'output'
          destination-github-username: YoungseoChoi23
          destination-repository-name: mmc-frontend
          user-email: ${{ secrets.EMAIL }} 
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
