name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      # Mustache 설치
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      
      # Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # yarn 설치
      - name: Install yarn
        run: npm install -g yarn

      # 의존성 설치
      - name: Install Dependencies
        run: yarn install 

      # React 빌드
      - name: Build
        run: yarn vite build

      # build.sh 실행
      - name: creates output
        run: sh ./bookduck/build.sh

      # 다른 저장소로 푸시
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }} 
        with:
          source-directory: 'output'
          destination-github-username: YoungseoChoi23
          destination-repository-name: mmc-frontend
          user-email: ${{ secrets.EMAIL }} 
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      # 푸시 후 변수 확인
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
